# Generated by Django 4.1.7 on 2023-06-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_notificationson_profile_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workingat',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
