# Generated by Django 4.1.7 on 2023-06-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_workingat_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='no_of_posts',
        ),
    ]
