# Generated by Django 4.1.7 on 2023-06-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_no_of_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dfollowers',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='dfollowing',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='dposts',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
