# Generated by Django 4.1.7 on 2023-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_dfollowers_profile_dfollowing_profile_dposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('followed', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('pimg', models.ImageField(default='blank-profile-picture.png', upload_to='profileimgs')),
                ('file', models.FileField(blank=True, null=True, upload_to='posts')),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('caption', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
